
namespace BeatSaberDownloader.Data.Enums
{
    public enum Environment
    {
        DefaultEnvironment = 1, 
        TriangleEnvironment = 2, 
        NiceEnvironment = 3, 
        BigMirrorEnvironment = 4, 
        KDAEnvironment = 5, 
        MonstercatEnvironment = 6, 
        CrabRaveEnvironment = 7, 
        DragonsEnvironment = 8, 
        OriginsEnvironment = 9, 
        PanicEnvironment = 10, 
        RocketEnvironment = 11, 
        GreenDayEnvironment = 12, 
        GreenDayGrenadeEnvironment = 13, 
        TimbalandEnvironment = 14, 
        FitBeatEnvironment = 15, 
        LinkinParkEnvironment = 16, 
        BTSEnvironment = 17, 
        KaleidoscopeEnvironment = 18, 
        InterscopeEnvironment = 19, 
        SkrillexEnvironment = 20, 
        BillieEnvironment = 21, 
        HalloweenEnvironment = 22, 
        GagaEnvironment = 23, 
        GlassDesertEnvironment = 24, 
        MultiplayerEnvironment = 25, 
        WeaveEnvironment = 26, 
        PyroEnvironment = 27, 
        EDMEnvironment = 28, 
        TheSecondEnvironment = 29, 
        LizzoEnvironment= 30, 
        TheWeekndEnvironment = 31, 
        RockMixtapeEnvironment = 32, 
        Dragons2Environment = 33, 
        Panic2Environment = 34, 
        QueenEnvironment = 35, 
        LinkinPark2Environment = 36, 
        TheRollingStonesEnvironment = 37, 
        LatticeEnvironment = 38, 
        DaftPunkEnvironment = 39, 
        HipHopEnvironment = 40, 
        ColliderEnvironment = 41, 
        BritneyEnvironment = 42, 
        Monstercat2Environment = 43, 
        MetallicaEnvironment = 44,
        Halloween2Environment = 45,
        GridEnvironment = 46
    }
}
